import { BookOpen, Boxes, Cable, ChevronRight, CircuitBoard, Cpu, Gauge, GitPullRequest, HardDrive, MemoryStick, PlugZap, Server, ShieldCheck, Thermometer } from 'lucide-react';

const chapters = [
  { icon: MemoryStick, title: 'Start with memory fit', text: 'Weights, runtime buffers and KV cache must fit before any speed claim matters. Addressable VRAM is different from the sum printed on split-memory boards.' },
  { icon: Gauge, title: 'Tokens per second need a profile', text: 'Model, quantization, engine, context, batch, backend and power limit all change throughput. Only identical profiles belong in one ranking.' },
  { icon: CircuitBoard, title: 'PCIe slots are not equal', text: 'A physical x16 connector may run at x16, x8 or x4 and may share lanes with M.2 storage. Multi-GPU plans need the board block diagram.' },
  { icon: PlugZap, title: 'Plan the wall, not just the PSU', text: 'Account for conversion loss, sustained circuit limits, transient excursions and other devices already sharing the branch circuit.' },
  { icon: Thermometer, title: 'Every watt becomes heat', text: 'A 1,500 W system emits roughly 5,100 BTU/h into the room. Cooling, airflow and noise determine whether a fast system is livable.' },
  { icon: Server, title: 'Enterprise cards need enterprise airflow', text: 'Passive accelerators assume strong front-to-back pressure. A desktop fan pointed at a heatsink is an experiment, not a qualified thermal design.' },
];

export function HomelabGuide({ onBuild }: { onBuild: () => void }) {
  return <main className="guide-page">
    <section className="guide-hero"><div><span className="section-kicker">AI HOMELAB FIELD GUIDE</span><h1>Buy capability.<br /><em>Not a pile of impressive specifications.</em></h1><p>A practical map from the model you want to run to memory, accelerators, host platform, power, cooling, software and total system cost.</p><button onClick={onBuild}>Open the guided builder <ChevronRight /></button></div><aside><BookOpen /><strong>Eight decisions</strong><span>Model → memory → speed → topology → power → cooling → software → price</span></aside></section>
    <section className="guide-path"><div className="section-heading"><span>THE DECISION PATH</span><div><h2>Use this order</h2><p>It prevents expensive compatibility mistakes.</p></div></div><div>{[
      ['01', 'Model', 'Choose the exact model, quantization and context.'], ['02', 'Memory', 'Calculate weights, KV cache and runtime reserve.'], ['03', 'Runtime', 'Confirm CUDA, ROCm, Metal or another supported backend.'], ['04', 'Accelerator', 'Compare exact tokens/sec, capacity and price.'], ['05', 'Platform', 'Allocate CPU lanes, slots, RAM and storage.'], ['06', 'Power', 'Size connectors, PSU, outlet and circuit.'], ['07', 'Thermals', 'Validate chassis, airflow, room heat and noise.'], ['08', 'Evidence', 'Open sources and understand every estimate.'],
    ].map(([number, title, text]) => <article key={number}><span>{number}</span><strong>{title}</strong><p>{text}</p></article>)}</div></section>
    <section className="guide-chapters"><div className="section-heading"><span>CORE CONCEPTS</span><div><h2>What actually decides a good AI homelab</h2><p>These are the constraints hidden by ordinary PC-part lists.</p></div></div><div>{chapters.map((chapter) => { const Icon = chapter.icon; return <article key={chapter.title}><span><Icon /></span><div><h3>{chapter.title}</h3><p>{chapter.text}</p></div></article>; })}</div></section>
    <section className="guide-stack"><div><span className="section-kicker">REFERENCE ARCHITECTURE</span><h2>A complete node is a system of constraints</h2><p>The builder audits each link and keeps unknown evidence visible.</p></div><div className="stack-map"><article><Cpu /><span><strong>CPU + memory</strong><small>Lanes · channels · offload</small></span></article><i /><article><CircuitBoard /><span><strong>Board + topology</strong><small>Slots · firmware · sharing</small></span></article><i /><article><Boxes /><span><strong>Accelerators</strong><small>VRAM · runtime · cooling</small></span></article><i /><article><PlugZap /><span><strong>PSU + circuit</strong><small>Cables · excursions · heat</small></span></article></div></section>
    <section className="guide-evidence"><div><ShieldCheck /><span><small>THE DATABASE PROMISE</small><h2>Measured, modeled and unknown never look the same.</h2><p>Every ranked result keeps its exact profile and source. A missing price is not zero dollars. A physical memory total is not automatically one addressable pool. A vendor TOPS claim is not tokens per second.</p></span></div><div><GitPullRequest /><span><small>CONTRIBUTE</small><h2>Bring a manual, listing or reproducible benchmark.</h2><p>Structured JSON records and automated checks keep community submissions reviewable. The contribution guide includes exact commands, evidence requirements and templates.</p><a href="https://github.com/Fahrnetic/compute-value" target="_blank" rel="noreferrer">Contribute on GitHub ↗</a></span></div></section>
    <section className="guide-checklist"><h2><Cable /> Before you buy</h2><div>{['Exact GPU variant and VRAM confirmed', 'Motherboard slot electrical widths mapped', 'Card width and chassis spacing verified', 'Native PSU connectors counted', 'Sustained wall load fits the circuit', 'Passive cards have engineered airflow', 'Runtime supports every selected GPU', 'Complete cost includes host and cooling', 'Benchmark profile matches your model', 'Unknown evidence reviewed manually'].map((item) => <span key={item}><ShieldCheck />{item}</span>)}</div></section>
  </main>;
}
